### ISSUE TITLE
key dump

### ISSUE THREAD

**Issue by ISeeTWizard** [shapecode/nya-doctrine-encrypt-bundle#1]
Hi

I was looking for the dumped key but unfortunately I can't find it.
Shouldn't it be in the main folder?

**Comment by nicklog** [comment]
Hey, 

it should be under "var/shapecode/encrypt".

Please report any bug oder issue you may find.

**Comment by ISeeTWizard** [comment]
unfortunately not...
I also put the config in the framework yaml file (like for michaeldegroot one) but that didn't change anything.
Does the file has a specific name? As for the original one it was .Defuse.key
I wanted to switch to yours as on the other one the console commands don't work but for yours it's ok...
It's just as I have a defuse key I want to reuse the same if possible

**Comment by nicklog** [comment]
The default config for the bundle is "%kernel.project_dir%/var/shapecode/encrypt".
The filename is encrypt. It has not a file extension.

**Comment by ISeeTWizard** [comment]
So to tell what I've done:
Symfony 4 is used
In framework.yml is put:
shapecode_nya_doctrine_encrypt:
    #  If you want, you can use your own Encryptor. Encryptor must implements EncryptorInterface interface
    #  Default: defuse
    encryptor: defuse
    
    # Path where to store the keyfiles
    # Default: '%kernel.project_dir%'
    secret_directory_path: '%kernel.project_dir%'   

in my entity i've put use Shapecode\NYADoctrineEncryptBundle\Configuration\Encrypted; at the top
than on the column I wanted to encryt I've added
    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     * @Encrypted
     */

That is working all correctly but unfortunately this folder and file doesn't exist :(

**Comment by nicklog** [comment]
change secret_directory_path to '%kernel.project_dir%/encrypt.key'.
An encrypt.key file should created in your projectdir.

**Comment by ISeeTWizard** [comment]
I also saw that I can't check on UniqueEntity entry when encryption is activated
Is that correct that this can't be used?

**Comment by ISeeTWizard** [comment]
I got the file like that :)
perfect

**Comment by nicklog** [comment]
> I also saw that I can't check on UniqueEntity entry when encryption is activated
> Is that correct that this can't be used?

That is not possible becauce each value is encrypted in the database and cannot be compared

**Comment by ISeeTWizard** [comment]
ok thank you very much
is somehow strange that now file was generated from the base config here..
But now it's up and running :)

And for the duplicate entry I have to find another solution than

**Comment by ISeeTWizard** [comment]
Another question (sorry)
I just tried a for me worst case scenario (that is also why the console command needs to work) and I decrypted the entire database.
That worked perfectly and when I now let me show the data in my table there is no error but I simply see the correct data.
Did you optimize this as with the other encryption tools I always got errors when trying to display unencrypted data?
